name: farizi_s_application3
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.3.2 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.7
  intl: ^0.18.0
  flutter_localizations: 
    sdk: flutter
  connectivity_plus: ^5.0.2
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/MontserratRomanExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MontserratRomanBlack.ttf
          weight: 900
    - family: Mochiy Pop One
      fonts: 
        - asset: assets/fonts/MochiyPopOneRegular.ttf
          weight: 400
    - family: MuseoModerno
      fonts: 
        - asset: assets/fonts/MuseoModernoBold.ttf
          weight: 700
